import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar/>
      <body >{children}</body>
      </div>
   
  )
}
